const DEGREES_PER_MINUTE: number = 6
const DEGREES_PER_SECOND: number = 6
const DEGREES_PER_HOUR: number = 30
const MINUTES_DEGREES_PER_SECOND_TICK = 0.1
const HOURS_DEGREES_PER_MINUTE_TICK = 0.5

export {
  DEGREES_PER_SECOND,
  DEGREES_PER_HOUR,
  DEGREES_PER_MINUTE,
  HOURS_DEGREES_PER_MINUTE_TICK,
  MINUTES_DEGREES_PER_SECOND_TICK
}